# Generated by Django 4.0.3 on 2022-03-28 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64, null=True)),
                ('lastname', models.CharField(max_length=64, null=True)),
                ('type', models.CharField(choices=[('STD', 'Standard'), ('ADM', 'Admin')], default='STD', max_length=3)),
                ('is_verified', models.BooleanField(default=False)),
                ('bio', models.TextField(max_length=512, null=True)),
                ('sign_in_provider', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
